server:
  port: 5002

#spring:
#  redis:
#    host: 192.168.0.8
#    port: 16379
#    password: sxx.123

# 设置中文返回编码格式
spring.http.encoding.force: true
spring.http.encoding.charset: UTF-8
spring.http.encoding.enabled: true
server.tomcat.uri-encoding: UTF-8

# 加入 java 包 org.springframework.security ，需要进行身份验证，这里取消掉
security.basic.enabled: false